### ISSUE TITLE
0.214.2 Update breaks the mod

### ISSUE THREAD

**Issue by nilsroesel** [derekShaheen/SkToolbox-for-Valheim#3]
Commands are not known after the patch

**Comment by brianmiller** [comment]
Confirmed on my systems as well.

**Comment by nilsroesel** [comment]
As far from the logs i can tell its about missing methods

**Comment by trandall50** [comment]
> As far from the logs i can tell its about missing methods
> 
> ```
> [Info   : Unity Log] (SkToolbox) ->  (TOOLBOX) ->  (MODULE) ->  (NOTIFY) ->  (RECHECK 2) -> NAME: CC CONTROLLER | STATUS: ERROR
> [Warning: Unity Log] (SkToolbox) ->  (ERR) -> Error detected! | Field 'Terminal.m_output' not found. | SkToolboxValheim 
> [Error  : Unity Log] MissingFieldException: Field 'Terminal.m_output' not found.
> Stack trace:
> SkToolbox.SkModules.ModConsole.Update () (at <9e2daa46db4b4f78b2d8fa8d2ad65e73>:0)
> 
> [Error  : Unity Log] MissingFieldException: Field 'Terminal.m_output' not found.
> Stack trace:
> 
> [Error  : Unity Log] MissingFieldException: Field 'Terminal.m_output' not found.
> Stack trace:
> 
> [Info   : Unity 
> ```

Trying this mod for the first time today and getting the same error.
